services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: tj-jeans

  mysql:
    image: mysql:latest  # Use the latest version of MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: tj-jeans
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
