// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package views_admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home(username string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- ========================= Main ==================== --> <div class=\"main\"><div class=\"topbar\"><div class=\"toggle\"><ion-icon name=\"menu-outline\"></ion-icon></div><!-- <div class=\"search\">\r\n                    <label>\r\n                        <input type=\"text\" placeholder=\"Search here\">\r\n                        <ion-icon name=\"search-outline\"></ion-icon>\r\n                    </label>\r\n                </div> --><div class=\"user\"><img src=\"/platform/web/static_admin/images/customer01.jpg\" alt=\"\"></div></div><!-- ======================= Cards ================== --><div class=\"cardBox\"><div class=\"card\"><div><div class=\"numbers\">1,504</div><div class=\"cardName\">Daily Views</div></div><div class=\"iconBx\"><ion-icon name=\"eye-outline\"></ion-icon></div></div><div class=\"card\"><div><div class=\"numbers\">80</div><div class=\"cardName\">Total Orders Bought</div></div><div class=\"iconBx\"><ion-icon name=\"cart-outline\"></ion-icon></div></div><div class=\"card\"><div><div class=\"numbers\">284</div><div class=\"cardName\">Total Products Bought</div></div><div class=\"iconBx\"><ion-icon name=\"chatbubbles-outline\"></ion-icon></div></div><div class=\"card\"><div><div class=\"numbers\">IDR 7,842</div><div class=\"cardName\">Total Revenue (Xendit/Midtrans)</div></div><div class=\"iconBx\"><ion-icon name=\"cash-outline\"></ion-icon></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Page(true, username).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
